# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2e25279bdc7c7de5efd23349320cfb063778603efc5f9546baef3b232ad6fabebfae3237d31b796984cfd8b519bf1a73ef986887ad6f10c026cb02a0f9afac

test:
  secret_key_base: edb80d327589989ada6a8364e913b98e4b34c8db56c65c6cd7e94eec7cbe95a5e5eb4ae9373878a5d267974ef9f7a683b9b948ef67cc1730798922fe5c0f4f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
